// <auto-generated />
using EF_Tutorial.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Tutorial.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230904090553_NewDB")]
    partial class NewDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Tutorial.Models.JsonData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("jsonId")
                        .HasColumnType("int");

                    b.Property<int>("value1")
                        .HasColumnType("int");

                    b.Property<int>("value2")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("JsonData");

                    b.HasData(
                        new
                        {
                            id = 1,
                            date = "2022-03-01",
                            jsonId = 1,
                            value1 = 101,
                            value2 = 105
                        },
                        new
                        {
                            id = 2,
                            date = "2022-03-02",
                            jsonId = 1,
                            value1 = 110,
                            value2 = 117
                        },
                        new
                        {
                            id = 3,
                            date = "2022-03-03",
                            jsonId = 1,
                            value1 = 102,
                            value2 = 120
                        },
                        new
                        {
                            id = 4,
                            date = "2022-03-04",
                            jsonId = 1,
                            value1 = 105,
                            value2 = 104
                        },
                        new
                        {
                            id = 5,
                            date = "2022-03-05",
                            jsonId = 1,
                            value1 = 120,
                            value2 = 102
                        },
                        new
                        {
                            id = 6,
                            date = "2022-03-06",
                            jsonId = 1,
                            value1 = 117,
                            value2 = 110
                        },
                        new
                        {
                            id = 7,
                            date = "2022-03-07",
                            jsonId = 1,
                            value1 = 105,
                            value2 = 101
                        },
                        new
                        {
                            id = 8,
                            date = "2022-03-01",
                            jsonId = 2,
                            value1 = 148,
                            value2 = 103
                        },
                        new
                        {
                            id = 9,
                            date = "2022-03-02",
                            jsonId = 2,
                            value1 = 135,
                            value2 = 136
                        },
                        new
                        {
                            id = 10,
                            date = "2022-03-03",
                            jsonId = 2,
                            value1 = 136,
                            value2 = 109
                        },
                        new
                        {
                            id = 11,
                            date = "2022-03-04",
                            jsonId = 2,
                            value1 = 123,
                            value2 = 109
                        },
                        new
                        {
                            id = 12,
                            date = "2022-03-05",
                            jsonId = 2,
                            value1 = 150,
                            value2 = 128
                        },
                        new
                        {
                            id = 13,
                            date = "2022-03-06",
                            jsonId = 2,
                            value1 = 145,
                            value2 = 110
                        },
                        new
                        {
                            id = 14,
                            date = "2022-03-07",
                            jsonId = 2,
                            value1 = 109,
                            value2 = 138
                        },
                        new
                        {
                            id = 15,
                            date = "2022-03-01",
                            jsonId = 3,
                            value1 = 150,
                            value2 = 104
                        },
                        new
                        {
                            id = 16,
                            date = "2022-03-02",
                            jsonId = 3,
                            value1 = 126,
                            value2 = 114
                        },
                        new
                        {
                            id = 17,
                            date = "2022-03-03",
                            jsonId = 3,
                            value1 = 135,
                            value2 = 109
                        },
                        new
                        {
                            id = 18,
                            date = "2022-03-04",
                            jsonId = 3,
                            value1 = 101,
                            value2 = 149
                        },
                        new
                        {
                            id = 19,
                            date = "2022-03-05",
                            jsonId = 3,
                            value1 = 111,
                            value2 = 123
                        },
                        new
                        {
                            id = 20,
                            date = "2022-03-06",
                            jsonId = 3,
                            value1 = 145,
                            value2 = 118
                        },
                        new
                        {
                            id = 21,
                            date = "2022-03-07",
                            jsonId = 3,
                            value1 = 139,
                            value2 = 145
                        },
                        new
                        {
                            id = 22,
                            date = "2022-03-01",
                            jsonId = 4,
                            value1 = 120,
                            value2 = 141
                        },
                        new
                        {
                            id = 23,
                            date = "2022-03-02",
                            jsonId = 4,
                            value1 = 132,
                            value2 = 109
                        },
                        new
                        {
                            id = 24,
                            date = "2022-03-03",
                            jsonId = 4,
                            value1 = 142,
                            value2 = 150
                        },
                        new
                        {
                            id = 25,
                            date = "2022-03-04",
                            jsonId = 4,
                            value1 = 115,
                            value2 = 110
                        },
                        new
                        {
                            id = 26,
                            date = "2022-03-05",
                            jsonId = 4,
                            value1 = 148,
                            value2 = 145
                        },
                        new
                        {
                            id = 27,
                            date = "2022-03-06",
                            jsonId = 4,
                            value1 = 146,
                            value2 = 132
                        },
                        new
                        {
                            id = 28,
                            date = "2022-03-07",
                            jsonId = 4,
                            value1 = 125,
                            value2 = 118
                        },
                        new
                        {
                            id = 29,
                            date = "2022-03-01",
                            jsonId = 5,
                            value1 = 135,
                            value2 = 128
                        },
                        new
                        {
                            id = 30,
                            date = "2022-03-02",
                            jsonId = 5,
                            value1 = 130,
                            value2 = 123
                        },
                        new
                        {
                            id = 31,
                            date = "2022-03-03",
                            jsonId = 5,
                            value1 = 145,
                            value2 = 128
                        },
                        new
                        {
                            id = 32,
                            date = "2022-03-04",
                            jsonId = 5,
                            value1 = 141,
                            value2 = 125
                        },
                        new
                        {
                            id = 33,
                            date = "2022-03-05",
                            jsonId = 5,
                            value1 = 119,
                            value2 = 109
                        },
                        new
                        {
                            id = 34,
                            date = "2022-03-06",
                            jsonId = 5,
                            value1 = 126,
                            value2 = 148
                        },
                        new
                        {
                            id = 35,
                            date = "2022-03-07",
                            jsonId = 5,
                            value1 = 128,
                            value2 = 105
                        },
                        new
                        {
                            id = 36,
                            date = "2022-03-01",
                            jsonId = 6,
                            value1 = 132,
                            value2 = 132
                        },
                        new
                        {
                            id = 37,
                            date = "2022-03-02",
                            jsonId = 6,
                            value1 = 108,
                            value2 = 148
                        },
                        new
                        {
                            id = 38,
                            date = "2022-03-03",
                            jsonId = 6,
                            value1 = 127,
                            value2 = 140
                        },
                        new
                        {
                            id = 39,
                            date = "2022-03-04",
                            jsonId = 6,
                            value1 = 139,
                            value2 = 135
                        },
                        new
                        {
                            id = 40,
                            date = "2022-03-05",
                            jsonId = 6,
                            value1 = 101,
                            value2 = 110
                        },
                        new
                        {
                            id = 41,
                            date = "2022-03-06",
                            jsonId = 6,
                            value1 = 134,
                            value2 = 121
                        },
                        new
                        {
                            id = 42,
                            date = "2022-03-07",
                            jsonId = 6,
                            value1 = 115,
                            value2 = 149
                        },
                        new
                        {
                            id = 43,
                            date = "2022-03-01",
                            jsonId = 7,
                            value1 = 137,
                            value2 = 147
                        },
                        new
                        {
                            id = 44,
                            date = "2022-03-02",
                            jsonId = 7,
                            value1 = 124,
                            value2 = 127
                        },
                        new
                        {
                            id = 45,
                            date = "2022-03-03",
                            jsonId = 7,
                            value1 = 147,
                            value2 = 130
                        },
                        new
                        {
                            id = 46,
                            date = "2022-03-04",
                            jsonId = 7,
                            value1 = 124,
                            value2 = 130
                        },
                        new
                        {
                            id = 47,
                            date = "2022-03-05",
                            jsonId = 7,
                            value1 = 116,
                            value2 = 110
                        },
                        new
                        {
                            id = 48,
                            date = "2022-03-06",
                            jsonId = 7,
                            value1 = 127,
                            value2 = 122
                        },
                        new
                        {
                            id = 49,
                            date = "2022-03-07",
                            jsonId = 7,
                            value1 = 150,
                            value2 = 104
                        },
                        new
                        {
                            id = 50,
                            date = "2022-03-01",
                            jsonId = 8,
                            value1 = 120,
                            value2 = 119
                        },
                        new
                        {
                            id = 51,
                            date = "2022-03-02",
                            jsonId = 8,
                            value1 = 131,
                            value2 = 122
                        },
                        new
                        {
                            id = 52,
                            date = "2022-03-03",
                            jsonId = 8,
                            value1 = 139,
                            value2 = 115
                        },
                        new
                        {
                            id = 53,
                            date = "2022-03-04",
                            jsonId = 8,
                            value1 = 118,
                            value2 = 150
                        },
                        new
                        {
                            id = 54,
                            date = "2022-03-05",
                            jsonId = 8,
                            value1 = 129,
                            value2 = 142
                        },
                        new
                        {
                            id = 55,
                            date = "2022-03-06",
                            jsonId = 8,
                            value1 = 102,
                            value2 = 104
                        },
                        new
                        {
                            id = 56,
                            date = "2022-03-07",
                            jsonId = 8,
                            value1 = 150,
                            value2 = 133
                        },
                        new
                        {
                            id = 57,
                            date = "2022-03-01",
                            jsonId = 9,
                            value1 = 133,
                            value2 = 110
                        },
                        new
                        {
                            id = 58,
                            date = "2022-03-02",
                            jsonId = 9,
                            value1 = 128,
                            value2 = 135
                        },
                        new
                        {
                            id = 59,
                            date = "2022-03-03",
                            jsonId = 9,
                            value1 = 138,
                            value2 = 122
                        },
                        new
                        {
                            id = 60,
                            date = "2022-03-04",
                            jsonId = 9,
                            value1 = 114,
                            value2 = 143
                        },
                        new
                        {
                            id = 61,
                            date = "2022-03-05",
                            jsonId = 9,
                            value1 = 140,
                            value2 = 119
                        },
                        new
                        {
                            id = 62,
                            date = "2022-03-06",
                            jsonId = 9,
                            value1 = 147,
                            value2 = 140
                        },
                        new
                        {
                            id = 63,
                            date = "2022-03-07",
                            jsonId = 9,
                            value1 = 119,
                            value2 = 103
                        },
                        new
                        {
                            id = 64,
                            date = "2022-03-01",
                            jsonId = 10,
                            value1 = 105,
                            value2 = 141
                        },
                        new
                        {
                            id = 65,
                            date = "2022-03-02",
                            jsonId = 10,
                            value1 = 122,
                            value2 = 134
                        },
                        new
                        {
                            id = 66,
                            date = "2022-03-03",
                            jsonId = 10,
                            value1 = 110,
                            value2 = 127
                        },
                        new
                        {
                            id = 67,
                            date = "2022-03-04",
                            jsonId = 10,
                            value1 = 147,
                            value2 = 116
                        },
                        new
                        {
                            id = 68,
                            date = "2022-03-05",
                            jsonId = 10,
                            value1 = 104,
                            value2 = 119
                        },
                        new
                        {
                            id = 69,
                            date = "2022-03-06",
                            jsonId = 10,
                            value1 = 116,
                            value2 = 130
                        },
                        new
                        {
                            id = 70,
                            date = "2022-03-07",
                            jsonId = 10,
                            value1 = 117,
                            value2 = 131
                        },
                        new
                        {
                            id = 71,
                            date = "2022-03-01",
                            jsonId = 11,
                            value1 = 121,
                            value2 = 125
                        },
                        new
                        {
                            id = 72,
                            date = "2022-03-02",
                            jsonId = 11,
                            value1 = 135,
                            value2 = 146
                        },
                        new
                        {
                            id = 73,
                            date = "2022-03-03",
                            jsonId = 11,
                            value1 = 129,
                            value2 = 132
                        },
                        new
                        {
                            id = 74,
                            date = "2022-03-04",
                            jsonId = 11,
                            value1 = 133,
                            value2 = 123
                        },
                        new
                        {
                            id = 75,
                            date = "2022-03-05",
                            jsonId = 11,
                            value1 = 146,
                            value2 = 131
                        },
                        new
                        {
                            id = 76,
                            date = "2022-03-06",
                            jsonId = 11,
                            value1 = 146,
                            value2 = 141
                        },
                        new
                        {
                            id = 77,
                            date = "2022-03-07",
                            jsonId = 11,
                            value1 = 108,
                            value2 = 116
                        },
                        new
                        {
                            id = 78,
                            date = "2022-03-01",
                            jsonId = 12,
                            value1 = 113,
                            value2 = 125
                        },
                        new
                        {
                            id = 79,
                            date = "2022-03-02",
                            jsonId = 12,
                            value1 = 114,
                            value2 = 130
                        },
                        new
                        {
                            id = 80,
                            date = "2022-03-03",
                            jsonId = 12,
                            value1 = 124,
                            value2 = 145
                        },
                        new
                        {
                            id = 81,
                            date = "2022-03-04",
                            jsonId = 12,
                            value1 = 128,
                            value2 = 112
                        },
                        new
                        {
                            id = 82,
                            date = "2022-03-05",
                            jsonId = 12,
                            value1 = 128,
                            value2 = 141
                        },
                        new
                        {
                            id = 83,
                            date = "2022-03-06",
                            jsonId = 12,
                            value1 = 100,
                            value2 = 108
                        },
                        new
                        {
                            id = 84,
                            date = "2022-03-07",
                            jsonId = 12,
                            value1 = 120,
                            value2 = 123
                        },
                        new
                        {
                            id = 85,
                            date = "2022-03-01",
                            jsonId = 13,
                            value1 = 136,
                            value2 = 124
                        },
                        new
                        {
                            id = 86,
                            date = "2022-03-02",
                            jsonId = 13,
                            value1 = 145,
                            value2 = 122
                        },
                        new
                        {
                            id = 87,
                            date = "2022-03-03",
                            jsonId = 13,
                            value1 = 102,
                            value2 = 106
                        },
                        new
                        {
                            id = 88,
                            date = "2022-03-04",
                            jsonId = 13,
                            value1 = 127,
                            value2 = 149
                        },
                        new
                        {
                            id = 89,
                            date = "2022-03-05",
                            jsonId = 13,
                            value1 = 118,
                            value2 = 113
                        },
                        new
                        {
                            id = 90,
                            date = "2022-03-06",
                            jsonId = 13,
                            value1 = 140,
                            value2 = 132
                        },
                        new
                        {
                            id = 91,
                            date = "2022-03-07",
                            jsonId = 13,
                            value1 = 108,
                            value2 = 110
                        },
                        new
                        {
                            id = 92,
                            date = "2022-03-01",
                            jsonId = 14,
                            value1 = 115,
                            value2 = 117
                        },
                        new
                        {
                            id = 93,
                            date = "2022-03-02",
                            jsonId = 14,
                            value1 = 144,
                            value2 = 112
                        },
                        new
                        {
                            id = 94,
                            date = "2022-03-03",
                            jsonId = 14,
                            value1 = 129,
                            value2 = 148
                        },
                        new
                        {
                            id = 95,
                            date = "2022-03-04",
                            jsonId = 14,
                            value1 = 119,
                            value2 = 121
                        },
                        new
                        {
                            id = 96,
                            date = "2022-03-05",
                            jsonId = 14,
                            value1 = 118,
                            value2 = 113
                        },
                        new
                        {
                            id = 97,
                            date = "2022-03-06",
                            jsonId = 14,
                            value1 = 112,
                            value2 = 120
                        },
                        new
                        {
                            id = 98,
                            date = "2022-03-07",
                            jsonId = 14,
                            value1 = 150,
                            value2 = 149
                        },
                        new
                        {
                            id = 99,
                            date = "2022-03-01",
                            jsonId = 15,
                            value1 = 121,
                            value2 = 126
                        },
                        new
                        {
                            id = 100,
                            date = "2022-03-02",
                            jsonId = 15,
                            value1 = 107,
                            value2 = 100
                        },
                        new
                        {
                            id = 101,
                            date = "2022-03-03",
                            jsonId = 15,
                            value1 = 119,
                            value2 = 119
                        },
                        new
                        {
                            id = 102,
                            date = "2022-03-04",
                            jsonId = 15,
                            value1 = 128,
                            value2 = 147
                        },
                        new
                        {
                            id = 103,
                            date = "2022-03-05",
                            jsonId = 15,
                            value1 = 114,
                            value2 = 137
                        },
                        new
                        {
                            id = 104,
                            date = "2022-03-06",
                            jsonId = 15,
                            value1 = 133,
                            value2 = 100
                        },
                        new
                        {
                            id = 105,
                            date = "2022-03-07",
                            jsonId = 15,
                            value1 = 116,
                            value2 = 141
                        });
                });

            modelBuilder.Entity("EF_Tutorial.Models.Pump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PumpId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pumps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pump 1",
                            PumpId = 1,
                            Status = true,
                            Type = "Centrifugal Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pump 2",
                            PumpId = 2,
                            Status = false,
                            Type = "Jet Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pump 3",
                            PumpId = 3,
                            Status = false,
                            Type = "Piston Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pump 4",
                            PumpId = 4,
                            Status = false,
                            Type = "Centrifugal Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pump 5",
                            PumpId = 5,
                            Status = true,
                            Type = "Jet Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pump 6",
                            PumpId = 6,
                            Status = true,
                            Type = "Jet Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pump 7",
                            PumpId = 7,
                            Status = false,
                            Type = "Piston Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pump 8",
                            PumpId = 8,
                            Status = true,
                            Type = "Piston Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pump 9",
                            PumpId = 9,
                            Status = false,
                            Type = "Centrifugal Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pump 10",
                            PumpId = 10,
                            Status = true,
                            Type = "Jet Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pump 11",
                            PumpId = 11,
                            Status = false,
                            Type = "Jet Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pump 12",
                            PumpId = 12,
                            Status = true,
                            Type = "Centrifugal Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pump 13",
                            PumpId = 13,
                            Status = true,
                            Type = "Piston Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pump 14",
                            PumpId = 14,
                            Status = false,
                            Type = "Piston Pump",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pump 15",
                            PumpId = 15,
                            Status = true,
                            Type = "Centrifugal Pump",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EF_Tutorial.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test1@123.com",
                            Password = "test1",
                            UserId = 1,
                            Username = "test1"
                        });
                });

            modelBuilder.Entity("EF_Tutorial.Models.Pump", b =>
                {
                    b.HasOne("EF_Tutorial.Models.User", "User")
                        .WithMany("Pumps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EF_Tutorial.Models.User", b =>
                {
                    b.Navigation("Pumps");
                });
#pragma warning restore 612, 618
        }
    }
}
